name: deploy_developement
on:
  push:
    branches:
      - dev
jobs:
  checkout:
    runs-on: realworld-runner
    steps:
      - uses: actions/checkout@v4
  deploy:
    runs-on: realworld-runner
    needs: checkout
    steps:
      - name: deploy
        env:
          ENV: development
          PREFIX: DEV
          JWT_KEY: ${STAGE_JWT_KEY}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${STAGE_POSTGRES_PASSWORD}
          PORT: 3002
        run: |
         docker-compose --project-name realworld-${ENV} build
         docker-compose --project-name realworld-${ENV} up -d
         docker image prune -f
